# version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pinjamkelas-app
    container_name: pinjamkelas-app
    restart: unless-stopped
    ports:
      - "8001:80"    # laravel
      - "5174:5174"  # vite
    volumes:
      - ./:/var/www/html
      - .vhost.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: pinjamkelas-db
    restart: unless-stopped
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: pinjamkelas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/database/pinjamkelas:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
